In [9]:
import os
import sys

In [10]:
try:
    import numpy as np
except ImportError:
    print('Cannot import Numpy', file=sys.stderr)

In [11]:
a = ([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [12]:
b = ([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])

In [13]:
for c in a + b:
    print(c)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 20, 30]
[40, 50, 60]
[70, 80, 90]


In [14]:
np_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [15]:
np_b = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])

In [16]:
np_a + np_b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [17]:
import string

In [18]:
string.__all__

['ascii_letters',
 'ascii_lowercase',
 'ascii_uppercase',
 'capwords',
 'digits',
 'hexdigits',
 'octdigits',
 'printable',
 'punctuation',
 'whitespace',
 'Formatter',
 'Template']

In [19]:
'\x20' in string.printable

True

In [20]:
bytes(np_a)

b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00'

In [21]:
print(a)
print('python built-in list 3x3 size in bytes: ', sys.getsizeof(a))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
python built-in list 3x3 size in bytes:  88


In [22]:
print(np_a)
print('python numpy ndarray 3x3 size in bytes: ', sys.getsizeof(np_a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
python numpy ndarray 3x3 size in bytes:  184


In [23]:
import timeit

In [53]:
timeit.default_timer()

5186.392897903